<a href="https://colab.research.google.com/github/gmdeorozco/Pandas-Library/blob/main/load_client_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files
import io

In [2]:
uploaded = files.upload()

Saving NC Stre.xlsx to NC Stre.xlsx

In [3]:
df = pd.read_excel(io.BytesIO(uploaded['NC Stre.xlsx']))

In [4]:
df.head()

    ID        Nombre        Apellido   Amount  Trades  Rank  Inactive
0  371    Suban Yuri  Valle Olivares  13279.0      13     1       NaN
1   70         Cesar       Gutierrez  11229.0       9     2       NaN
2  165        Isaias          Flores  10300.0       8     3       NaN
3  432  Gustavo Josê    Laguna Lôpez   8260.0       5     4       NaN
4    3        Anyelo  Briones Flores   8045.0       5     5       NaN

In [5]:
df.set_index('ID', inplace=True)

In [6]:
df.head()

           Nombre        Apellido   Amount  Trades  Rank  Inactive
ID
371    Suban Yuri  Valle Olivares  13279.0      13     1       NaN
70          Cesar       Gutierrez  11229.0       9     2       NaN
165        Isaias          Flores  10300.0       8     3       NaN
432  Gustavo Josê    Laguna Lôpez   8260.0       5     4       NaN
3          Anyelo  Briones Flores   8045.0       5     5       NaN

In [8]:
df.fillna({'Inactive':0},inplace=True)

In [9]:
df.head()

           Nombre        Apellido   Amount  Trades  Rank  Inactive
ID
371    Suban Yuri  Valle Olivares  13279.0      13     1       0.0
70          Cesar       Gutierrez  11229.0       9     2       0.0
165        Isaias          Flores  10300.0       8     3       0.0
432  Gustavo Josê    Laguna Lôpez   8260.0       5     4       0.0
3          Anyelo  Briones Flores   8045.0       5     5       0.0

In [10]:
df.Inactive = df.Inactive.astype('int32')

In [11]:
df.Amount = df.Amount.astype('int32')

In [12]:
df.head()

           Nombre        Apellido  Amount  Trades  Rank  Inactive
ID
371    Suban Yuri  Valle Olivares   13279      13     1         0
70          Cesar       Gutierrez   11229       9     2         0
165        Isaias          Flores   10300       8     3         0
432  Gustavo Josê    Laguna Lôpez    8260       5     4         0
3          Anyelo  Briones Flores    8045       5     5         0

In [13]:
from google.colab import files

In [14]:
uploaded = files.upload()

Saving NC Stre.xlsx to NC Stre (1).xlsx

In [15]:
new_df = pd.read_excel(io.BytesIO(uploaded['NC Stre.xlsx']))

In [16]:
new_df.head()

    ID        Nombre        Apellido   Amount  Trades  Rank  Inactive
0  371    Suban Yuri  Valle Olivares  13279.0      13     1       NaN
1   70         Cesar       Gutierrez  11229.0       9     2       NaN
2  165        Isaias          Flores  10300.0       8     3       NaN
3  432  Gustavo Josê    Laguna Lôpez   8260.0       5     4       NaN
4    3        Anyelo  Briones Flores   8045.0       5     5       NaN